#!/bin/bash
# Installs staticgen - Static site generator from markdown
# Author Jashon Osala 2023
# github https://github.com/osala-eng

if [ $(id -u) -ne 0 ]; then
    echo -e "You must be root to install staticgen"
    echo -e "Try: sudo ./install"
    exit 1
fi

source lib/supportfiles
echo -e "Installing staticgen please wait"

INSTALLPATH="/opt/staticgen"
BINPATH="/bin/staticgen"
LOGPATH="/var/log/staticgen"
STATICGENTOOL="/opt/staticgen/bin/main.sh"
USER=""


# Create required directories if not available
mkdir -p "$INSTALLPATH" "$LOGPATH"

print_line "Installing files"
cp -r lib "$INSTALLPATH"/
cp -r bin "$INSTALLPATH"/

chown -hR "$USER":"$USER" $INSTALLPATH

chmod u+x $INSTALLPATH/bin/*

ln -s -f "$BINPATH" "$STATICGENTOOL"

