#!/bin/bash
# Installs staticgen - Static site generator from markdown
# Author Jashon Osala 2023
# github https://github.com/osala-eng

if [ $(id -u) -ne 0 ]; then
    echo -e "You must be root to install staticgen"
    echo -e "Try: sudo ./install"
    exit 1
fi


echo -e "Installing staticgen please wait"

INSTALLPATH="/opt/staticgen"
BINPATH="/usr/local/bin"
LOGPATH="/var/log/staticgen"
STATICGENTOOL="/opt/staticgen/bin/main.sh"

# Create required directories if not available
rm -rf "$INSTALLPATH"

mkdir -p "$INSTALLPATH" "$LOGPATH" "$BINPATH"

echo -e "Installing files"
cp -r lib "$INSTALLPATH"/
cp -r bin "$INSTALLPATH"/

chown -hR "$SUDO_USER":"$SUDO_USER" "$INSTALLPATH"
chown -hR "$SUDO_USER":"$SUDO_USER" "$LOGPATH"

chmod a+x $INSTALLPATH/bin/*
chmod a+x "$INSTALLPATH/bin/js"/*

ln -s -f "$STATICGENTOOL" "$BINPATH/staticgen"

staticgen --install-modules
