#!/bin/bash
# Contains support functions

# Dev null
NULL="/dev/null"
UPDATE=0

# Run apt update
run_update () {
	[[ $((UPDATE)) -eq 1 ]] && return;
	apt-get update -y;
	UPDATE=1;
}

# Check if a programme is available
check_program () {
	if ! command -v "$1" &> "$NULL"; then
		[[ $((UPDATE)) -eq 0 ]] && run_update
		apt-get install $1 -y;
	fi
}

# Gets filename without extension from path
get_filename () {
	temp="${1%.*}"
	filename="${temp##*/}"
}

# Convert markdown to HTML
convert_to_html () {
	INDIR="$1"; OUTDIR="$2";

	for line in ${INDIR}/*; do
		get_filename "$line"
	       	markdown < "$line" > "${OUTDIR}/${filename}.html";
	done
}
