#!/bin/bash
# Contains support functions

# Dev null
NULL="/dev/null"
UPDATE=0
showdown="/home/ubuntu/showdown-2.1.0/bin/showdown.js"

# Test empty dir
dir_is_empty() {
	test -e "$1/"* 2>/dev/null
	case $? in
	1) return 1 ;;
	*) return 0 ;;
	esac
}

# Run apt update
run_update() {
	[[ $((UPDATE)) -eq 1 ]] && return
	apt-get update -y
	UPDATE=1
}

# Local install configuration
local_install_config() {
	case $1 in
	"node") node_installer ;;
	*) apt-get install $1 -y ;;
	esac
}

# Check if a programme is available
check_program() {
	for i in $@; do
		if ! command -v "$i" &>"$NULL"; then
			[[ $((UPDATE)) -eq 0 ]] && run_update
			local_install_config $i
		fi
	done
}

# Gets filename without extension from path
get_filename() {
	local temp="${1%.*}"
	filename="${temp##*/}"
}

# Convert markdown to HTML
convert_to_html() {
	local indir="$1"
	local outdir="$2"

	for line in ${indir}/*; do
		get_filename "$line"
		showdown makehtml -i "$line" -o "${outdir}/${filename}.html"

		#markdown <"$line" >"${outdir}/${filename}.html"
	done
}

# Cleanup function
Cleanup() {
	for i in $@; do
		rm -rf "$i"
	done
}

# Nodejs Setup path and installs
node_js_setup() {
	export NODE_PATH="$(npm list -g | head -1)/node_modules"
	for module in $@; do
		echo -e "Checking for $module globally"
		if npm list -g | grep -q "$module"; then
			echo -e "$module found"
			continue
		else
			echo -e "$module not found Running npm install"
			npm install -g "$module"
		fi
	done
}

# Shebang install templates with the right bin bath
shebang_js() {
	local node_bin="#!$(which node)"
	for filename in $@; do
		sed -i "1s|^.*$|$node_bin|" "$filename"
	done
}

# Prints a line and appends an empty line at the end
print_line() {
	echo -e "$1"
	echo -e
}

# Remove metadata from files
remove_meta() {
	for filename in $@; do
		sed -i '/---/,/---/d' "$filename"
	done
}

# Run css build
run_sassy_css() {
	sass "$1" "$2"
}
